# -*- coding: utf-8 -*-
"""Statistics and Trends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdC45_nxe_vxavBASYLuCkfrk0XIp0LE
"""

from corner import corner
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats as ss
import seaborn as sns

def plot_relational_plot(df):
    for col in ['Route_Length_km', 'Delay_Minutes']:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    company_avgs = df.groupby('Company')[['Route_Length_km', 'Delay_Minutes']].mean().reset_index()
    fig, ax = plt.subplots(figsize=(9, 6))
    plt.plot(company_avgs['Company'], company_avgs['Route_Length_km'], marker='o', label='Avg Route Length [km]', color='royalblue')
    plt.plot(company_avgs['Company'], company_avgs['Delay_Minutes'], marker='s', label='Avg Delay [min]', color='orange')
    plt.title('Average Route Length and Delay by Company')
    plt.xlabel('Company')
    plt.ylabel('Value')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()
    plt.savefig('relational_plot.png')
    return

def plot_categorical_plot(df):
    df['Cost_kUSD'] = pd.to_numeric(df['Cost_kUSD'], errors='coerce')
    avg_cost = df.groupby('Company')['Cost_kUSD'].mean().reset_index()
    fig, ax = plt.subplots(figsize=(8,6))
    plt.bar(avg_cost['Company'], avg_cost['Cost_kUSD'], color='teal')
    plt.title('Average Shipping Cost by Company')
    plt.xlabel('Company')
    plt.ylabel('Average Cost [thousands USD]')
    plt.tight_layout()
    plt.show()
    plt.savefig('categorical_plot.png')
    return

def plot_statistical_plot(df):
    num_cols = ['Shipments', 'Avg_Weight_Tons', 'Route_Length_km', 'Delay_Minutes', 'Cost_kUSD']
    for col in num_cols:
      df[col] = pd.to_numeric(df[col], errors='coerce')

    corr = df[num_cols].corr()
    mask = np.triu(np.ones_like(corr, dtype=bool))

    fig, ax = plt.subplots(figsize=(8, 6))
    sns.heatmap(corr,mask=mask,annot=True,cmap='coolwarm',vmin=-1, vmax=1,square=True,linewidths=0.8,cbar_kws={'shrink': .8})
    plt.title('Correlation Heatmap (Lower Triangular)')
    plt.tight_layout()
    plt.show()
    plt.savefig('statistical_plot.png')
    return

def statistical_analysis(df, col: str):
    mean = df[col].mean()
    stddev = df[col].std()
    skew = df[col].skew()
    excess_kurtosis = df[col].kurtosis()
    return mean, stddev, skew, excess_kurtosis

def preprocessing(df):
    # You should preprocess your data in this function and
    df['Cost_kUSD'] = pd.to_numeric(df['Cost_kUSD'], errors='coerce')
    avg_cost = df.groupby('Company')['Cost_kUSD'].mean().reset_index()
    for col in ['Route_Length_km', 'Delay_Minutes']:
      df[col] = pd.to_numeric(df[col], errors='coerce')
    company_avgs = df.groupby('Company')[['Route_Length_km', 'Delay_Minutes']].mean().reset_index()
    # make use of quick features such as 'describe', 'head/tail' and 'corr'.

    # Display the first few rows
    print("DataFrame Head:")
    display(df.head())

    # Display the last few rows
    print("\nDataFrame Tail:")
    display(df.tail())

    # Display descriptive statistics
    print("\nDataFrame Description:")
    display(df.describe())

    # Display the correlation matrix for numerical columns
    print("\nDataFrame Correlation Matrix:")
    display(df.corr(numeric_only=True))

    return df, company_avgs, avg_cost

def writing(moments, col):
    print(f'For the attribute {col}:')
    print(f'Mean = {moments[0]:.2f}, '
          f'Standard Deviation = {moments[1]:.2f}, '
          f'Skewness = {moments[2]:.2f}, and '
          f'Excess Kurtosis = {moments[3]:.2f}.')

    # Interpret Skewness
    skewness = moments[2]
    if skewness > 0.5:
        skew_interpretation = "right skewed (positively skewed)"
    elif skewness < -0.5:
        skew_interpretation = "left skewed (negatively skewed)"
    else:
        skew_interpretation = "approximately symmetric (not skewed)"

    # Interpret Kurtosis (Excess Kurtosis)
    excess_kurtosis = moments[3]
    if excess_kurtosis > 0:
        kurtosis_interpretation = "leptokurtic (heavier tails than a normal distribution)"
    elif excess_kurtosis < 0:
        kurtosis_interpretation = "platykurtic (lighter tails than a normal distribution)"
    else:
        kurtosis_interpretation = "mesokurtic (similar to a normal distribution)"

    print(f'The data is {skew_interpretation} and is {kurtosis_interpretation}.')
    return

def main():
    df = pd.read_csv('data1.csv')
    df, company_avgs, avg_cost = preprocessing(df)
    col = 'Delay_Minutes'
    plot_relational_plot(df)
    plot_statistical_plot(df)
    plot_categorical_plot(df)
    moments = statistical_analysis(df, col)
    writing(moments, col)
    return

if __name__ == '__main__':
    main()